### ISSUE TITLE
cup build error

### ISSUE THREAD

**Issue by h-tx** [styletron/styletron#428]
Hello,

I keep getting this error when trying to build the project.
```
Building package...
⠦ Running build:node...
⠦ Running build:browser (es5)...
⠦ Running build:browser (es2015)...
✘ build:browser (es2017) failed.
✘ build:browser (es2015) failed.
✔ flowlibdef succeeded.
Error: [BABEL] project/node_modules/styletron-react/src/index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}


If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
✘ build:browser (es5) failed.
node_modules/@babel/preset-stage-3/lib/index.js")
Error: [BABEL] project/node_modules/styletron-react/src/index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}


If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
✘ build:node failed.
node_modules/@babel/preset-stage-3/lib/index.js")
Error: [BABEL] project/node_modules/styletron-react/src/index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}


If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "project/node_modules/styletron-react/node_modules/@babel/preset-stage-3/lib/index.js")
Error: [BABEL] project/node_modules/styletron-react/src/index.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}


If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "project/node_modules/styletron-react/node_modules/@babel/preset-stage-3/lib/index.js")
npm verb lifecycle styletron-react@6.0.2~build: unsafe-perm in lifecycle true
npm verb lifecycle styletron-react@6.0.2~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:project/node_modules/styletron-react/node_modules/.bin:project/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:project/node_modules/styletron-react/node_modules/.bin:project/node_modules/.bin:/Users/user/ImageMagick-7.0.10/bin:/projects/go/bin:/usr/local/Cellar/libpq/11.5/bin:/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/Users/user/Library/Android/sdk/platform-tools:/usr/local/mysql/bin:/Users/user/.local/bin
npm verb lifecycle styletron-react@6.0.2~build: CWD: project/node_modules/styletron-react
npm sill lifecycle styletron-react@6.0.2~build: Args: [ '-c', 'cup build --force-flow' ]
npm sill lifecycle styletron-react@6.0.2~build: Returned: code: 1  signal: null
npm info lifecycle styletron-react@6.0.2~build: Failed to exec build script
npm verb stack Error: styletron-react@6.0.2 build: `cup build --force-flow`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid styletron-react@6.0.2
npm verb cwd project/node_modules/styletron-react
npm verb Darwin 21.4.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm verb node v14.16.0
npm verb npm  v6.14.11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! styletron-react@6.0.2 build: `cup build --force-flow`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the styletron-react@6.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 3354ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2022-07-15T10_04_13_580Z-debug.log
npm verb lifecycle styletron-react@6.0.2~prepublish: unsafe-perm in lifecycle true
npm verb lifecycle styletron-react@6.0.2~prepublish: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:project/node_modules/styletron-react/node_modules/.bin:project/node_modules/.bin:/Users/user/ImageMagick-7.0.10/bin:/projects/go/bin:/usr/local/Cellar/libpq/11.5/bin:/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/Users/user/Library/Android/sdk/platform-tools:/usr/local/mysql/bin:/Users/user/.local/bin
npm verb lifecycle styletron-react@6.0.2~prepublish: CWD: project/node_modules/styletron-react
npm sill lifecycle styletron-react@6.0.2~prepublish: Args: [ '-c', 'npm run build' ]
npm sill lifecycle styletron-react@6.0.2~prepublish: Returned: code: 1  signal: null
npm info lifecycle styletron-react@6.0.2~prepublish: Failed to exec prepublish script
npm verb stack Error: styletron-react@6.0.2 prepublish: `npm run build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid styletron-react@6.0.2
npm verb cwd project/node_modules/styletron-react
npm verb Darwin 21.4.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "link"
npm verb node v14.16.0
npm verb npm  v6.14.11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! styletron-react@6.0.2 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the styletron-react@6.0.2 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]


```
Any idea what could be the issue and a possible workaround without forking and removing the script?

**Comment by h-tx** [comment]
The latest version doesn't have the issue
